#!/bin/sh -e
clear
# Copyright BYETFAST
# SSH TLS
# Miner por: noncepool

bash=$(echo $BASH)

if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

versao=1.0.0

wallet=$1
if [ "$1" = ""  ]
then
echo "			\033[41;1;37m Minerar BTC $versao \033[0m "				
sleep 1
echo "$verde Forma de USO: \033[0m"
echo "sudo sh $0 $vermelho Carteira de BTC \033[0m  \n "
echo "$verde Exemplo:\033[0m"
echo "sudo sh $0 $vermelho $wallet2 \033[0m   \n"
exit 0
fi

echo "			\033[41;1;37m Minerar BTC $versao \033[0m "	
sleep 1
echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
sleep 1
echo "\033[01;31m	 * Minerar BITCOIN zpool.ca \033[0m   \n"
sleep 1
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sleep 1
sudo apt-get update
sudo apt-get install build-essential libcurl4-openssl-dev gcc make git nano autoconf automake -y > /dev/null
sudo apt-get install screen -y
sudo rm -r miner
git clone https://github.com/noncepool/cpuminer-yescrypt.git miner
sleep 1

echo "\033[44;1;37m Configurando e Compilando Recursos.....     \033[0m "
sleep 1
cd miner
./autogen.sh
./configure CFLAGS="-O3"
make
cd miner
sudo mv minerd /usr/local/bin/

echo "\033[01;41mInicializando Mineração......     \033[0m \n "
sleep 1
echo "\033[01;31mSCRIPT  INICIA SCREEN AUTOMATICO..."
sleep 3
echo "\033[01;32m ETAPA [2/2] completa"
sleep 3
clear
screen -dmS miner minerd -a yescrypt stratum+tcp://mine.zpool.ca:6233 -u $wallet -B
echo "\033[01;31m Sua Mineraçao Foi aberta em [ screen -x miner ] .. Abrindo sessao em 3segundos"
sleep 3
screen -x miner
